name: Release

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: Release')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install deps
        run: npm ci
      - name: Check if release should be published
        shell: bash
        id: semantic
        run: |
          npx semantic-release |& tee -a semantic-log.txt
          grep -E "(Published release)" semantic-log.txt || echo norelease
          echo "::set-output name=SEMANTIC_LOG::$(grep -E "(Published release)" semantic-log.txt || echo norelease)"
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
